"""empty message

Revision ID: d38d1b956466
Revises: 
Create Date: 2019-12-20 13:23:28.139956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38d1b956466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.String(length=64), nullable=True),
    sa.Column('employer', sa.Boolean(), nullable=False),
    sa.Column('male', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address_street', sa.String(length=20), nullable=False),
    sa.Column('address_city', sa.String(length=15), nullable=False),
    sa.Column('address_province', sa.String(length=20), nullable=False),
    sa.Column('address_country', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('phone_for_contact', sa.String(length=20), nullable=False),
    sa.Column('address_of_job', sa.Text(), nullable=False),
    sa.Column('address_province', sa.String(length=20), nullable=False),
    sa.Column('address_country', sa.String(length=15), nullable=False),
    sa.Column('applied_for_this_job', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
